a=("Mango","Kiwi","Bengan","Krow","5678","Savar")
print("The original tuple is =",a)
a=list(a)
b=input("Enter a element you want to remove:")
a.remove(b)
a=tuple(a)
print("The end tuple is =",a)
